---
title: "git_01"
author: "Math_115"
date: "Spring semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
Five little girls, of Five, Four, Three, Two, One:  
Rolling on the hearthrug, full of tricks and fun.   

Five rosy girls, in years from Ten to Six:  
Sitting down to lessons - no more time for tricks.   

Five growing girls, from Fifteen to Eleven:  
"Just the place for a Snark!" the Bellman cried,    
   As he landed his crew with care;    
Supporting each man on the top of the tide    
   By a finger entwined in his hair.    

"Just the place for a Snark! I have said it twice:    

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Curtains forcing their will  
against the wind,  
children sleep,  
exchanging dreams with  
seraphim. The city  
drags itself awake on  
subway straps; and  
I, an alarm, awake as a  
rumor of war  
lie stretching into dawn  
unasked and unheeded.  